### ISSUE TITLE
Possible to set blank limit (and probably other limits) beyond permissible range.

### ISSUE THREAD

**Issue by ajanata** [ajanata/PretendYoureXyzzy#103]
The server doesn't verify that the client is passing in values within the allowed range, so something like this:

``` javascript
$('#blanks_limit_30')[0].options.add($("<option value='90'>90</option>"))
```

will allow you to have 90 blank cards in a game (if you are the host in game 30).

**Comment by Jimi-James** [comment]
I would call this a feature, not a bug. Why not allow players to have more blank cards than 30?
