### ISSUE TITLE
Would it be possible to make this a maven project for easier building?

### ISSUE THREAD

**Issue by chamunks** [ajanata/PretendYoureXyzzy#129]
http://stackoverflow.com/questions/9264417/how-to-mavenize-a-standard-eclipse-project-but-only-for-some-dependencies

It would make it easier to test.  I could rig this into my CI server for auto deployment and testing from git push's

**Comment by ajanata** [comment]
Crossed paths with you on this. It still needs a bit of cleaning up, but it ought to be sufficient for now.

**Comment by chamunks** [comment]
You sir/madam are a god thank you :D
