### ISSUE TITLE
My stack trace on "mvn -X clean package"

### ISSUE THREAD

**Issue by chamunks** [ajanata/PretendYoureXyzzy#133]
Continuation of #129 
I have some output for you to take a look at.  https://gist.github.com/0e556877124fcd31f23b

**Comment by NightDevel** [comment]
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFilesExist failed with message:
Some required files are missing:
/root/PretendYoureXyzzy/build.properties
 

cp build.properties.example build.properties 

(or write your own build.properties.)

**Comment by chamunks** [comment]
Oh fantastic that was a build success.  Now to see how well this runs with no instructions.

**Comment by ajanata** [comment]
There is a bit of a guide in the commit message for 832bcd8. There is also https://github.com/ajanata/PretendYoureXyzzy/wiki/Quickstart-Guide but it sounds like you are beyond that point.

I will update the base README with more information tonight.
