### ISSUE TITLE
Wiki Missing Information: Needs information on Invocation.

### ISSUE THREAD

**Issue by chamunks** [ajanata/PretendYoureXyzzy#134]
https://github.com/ajanata/PretendYoureXyzzy/wiki/Quickstart-Guide This gets me a successful ROOT.jar but does not show me what the invocation would look like.  For example "java -jar ROOT.jar" does nothing.

**Comment by NightDevel** [comment]
If you do mvn clean package war:exploded jetty:run, visit localhost:8080

if you do mvn clean package war:war, you'll get a .war to deploy to a tomcat instance.

**Comment by chamunks** [comment]
Ah so the command that worked was.  

mvn clean package war:war
