### ISSUE TITLE
Already played Cards staying in Inventory

### ISSUE THREAD

**Issue by vainamov** [ajanata/PretendYoureXyzzy#151]
Sometimes when you play a card, it won't get removed from your hand. When you don't noticed and try to throw it again, you get an error saying you don't have this card and then you're stuck.
Maybe either check at the beginning of each round, if there're cards the player don't have anymore and remove them or let the user choose another card instead if he accidentally picked one.

**Comment by ajanata** [comment]
I still have no idea why the client desyncs like that, but if you type `/sync` into the chat box, or just reload the page, they'll go away.
