### ISSUE TITLE
Internal error with postgresql

### ISSUE THREAD

**Issue by AnonEstranho** [ajanata/PretendYoureXyzzy#155]
Hello guys. I have all things in my vps, database and website done. 

The problem is, I don't have card decks, and when I start the game and enter the main lobby, the room list, the chat gives internal error.

The db works, I can connect to it with navicat in my windows pc.

You can see for youself here: http://138.68.65.196/px/game.jsp

Details:

Ubuntu
PostgreSQL, with database called cahdb, and user cah.
I can connect to the database via remote, using navicat in my pc. I can see the database.
I create the database with the default .sql provided in this github.

```
	    <property name="hibernate.connection.driver_class">org.postgresql.Driver</property>
        <property name="hibernate.dialect">org.postgresql.Driver</property>
        <property name="hibernate.connection.url">jdbc:postgresql://138.68.65.196:5432/DATABASENAME</property>
        <property name="hibernate.connection.username">DATABASEUSERNAME</property>
        <property name="hibernate.connection.password">DATABASEPASSWORD</property>
        <property name="transaction.factory_class">org.hibernate.transaction.JDBCTransactionFactory</property>
```

Anyone has any insight to fix this?

**Comment by ajanata** [comment]
Cleaning up old issues and closing this as it is over a year old. Please re-open if you still want assistance.
