### ISSUE TITLE
Variable $cah is undefined.

### ISSUE THREAD

**Issue by 121GWJolt** [ajanata/PretendYoureXyzzy#156]
Various 500 Errors being thrown frequently.  When page loads, if it doesn't work, it states that this is undefined.  Attempting to load the offending JS file actually CRASHED my FireFox instance.  Cross-server issue; renders game unplayable.  Confirmed to affect multiple parties in vastly different locations at the same time.

**Comment by ajanata** [comment]
The servers had been getting massively overloaded. I'm making changes in the near future to help with that... Not really any code bugs, though.
