### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by devgianlu** [ajanata/PretendYoureXyzzy#159]
I am ready to help developing and fixing all the bugs in this game. I am working on a related project based on this repo so I've pretty much read the entire code. Now my question is, as this project is idle since some time, will someone merge my pull requests?

**Comment by A3K** [comment]
Would be keen to see your fork if the original repo doesn't pull it in

**Comment by devgianlu** [comment]
I've decided that I'll rewrite the entire game. I'll create a new repo on my own (still giving credits to this one).
