### ISSUE TITLE
Has the site been hacked ?

### ISSUE THREAD

**Issue by GregFdz** [ajanata/PretendYoureXyzzy#162]
Hi,
it seems that the site is being laggy, these days -and not just for me. The chat is filled with "ERROR" messages and bots named "increase your security" are ruining the game.
What's happening ?
Thanks

**Comment by ajanata** [comment]
Which server and when specifically (include a time zone).

**Comment by GregFdz** [comment]
It was on pyx-1, last night between (12/12) 11pm and (12/13) 1am (Paris)
