### ISSUE TITLE
Error with maven

### ISSUE THREAD

**Issue by dawidekziaja** [ajanata/PretendYoureXyzzy#163]
I get this error when building using maven:
`[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.3.0.v20150612:run (default-cli) on project pyx: Unable to parse configuration of mojo org.eclipse.jetty:jetty-maven-plugin:9.3.0.v20150612:run for parameter resourceBases: Cannot set 'resourceBases' in class org.eclipse.jetty.maven.plugin.JettyWebAppContext: InvocationTargetException: file:///home/dawid/PretendYoureXyzzy/target/ZY is not an existing directory. -> [Help 1]
`

**Comment by ajanata** [comment]
That's odd, does it still fail if you create the directory it's complaining about manually?

**Comment by dawidekziaja** [comment]
Yes, but I have managed to solve the issue. I referred to the readme to get the build command, but then I noticed that the wiki says I should run using `war:exploded`, and adding that parameter fixed the issue.

**Comment by ajanata** [comment]
I'll add that to the readme.
