### ISSUE TITLE
Configuring admin access on personal server

### ISSUE THREAD

**Issue by ceb515** [ajanata/PretendYoureXyzzy#165]
I started a new server for my friends to use, but I am getting an error when I try to connect to the admin panel or do anything as an admin.

> HTTP Status 403 - Access is restricted to known hosts

How do I add myself to the list of known hosts?

**Comment by ajanata** [comment]
Add your IP address to https://github.com/ajanata/PretendYoureXyzzy/blob/master/src/main/java/net/socialgamer/cah/Constants.java#L52 (and probably remove mine). I'm thinking about moving this out to the configuration file so it's easier to find, assuming that doesn't cause a chain reaction of changes that takes more than a few minutes to do.
