### ISSUE TITLE
Global chat enabled API endpoint

### ISSUE THREAD

**Issue by devgianlu** [ajanata/PretendYoureXyzzy#168]
Hi,
I'm the owner of the Pretend You're Xyzzy app. Since I fixed a major issue (#161) in my app, I can now proceed with adding more features. In particular, it would be useful to have sent whether the global chat is enabled. This could be easily done in the FirstLoad handler. 

I've already made a pull request (#169). I am also the owner of the https://github.com/devgianlu/PYX-Reloaded repo and therefore I have a deep knowledge of your game, if you need help.    

Right now I'm sending an empty message and I determine if the chat enabled check has been passed based on the error given.

**Comment by ajanata** [comment]
For the record, this is already implemented in [cah.config.js](https://pyx-1.pretendyoure.xyz/zy/js/cah.config.js) in the [JavascriptConfigServlet](https://github.com/ajanata/PretendYoureXyzzy/blob/master/src/main/java/net/socialgamer/cah/servlets/JavascriptConfigServlet.java#L87), though this seems like a better way to do it.

Also note that this setting technically can change at any time, but in practice (for my servers, at least), it would only change shortly after the server starts.

**Comment by devgianlu** [comment]
For now, I think I'll use the JavascriptConfigServlet, let me know when you'll update the server so that I can switch to the newer method.

**Comment by ajanata** [comment]
This should be deployed on my servers now. It'd probably be a good idea for some more server configuration information to be included in that response and not just on the js configuration servlet, but if I do add that I'll leave this for backwards compatibility at least for a while.

**Comment by devgianlu** [comment]
I'm still the JS handler because it has some more interesting stuff. Anyway you could dump all the keys and values into a map returned with FirstLoad. I'll make a pull request to explain better.
