### ISSUE TITLE
Server advanced ping

### ISSUE THREAD

**Issue by devgianlu** [ajanata/PretendYoureXyzzy#170]
In my app, I've implement the possibility to add custom server and therefore I need some way of telling if the server is up. A simple ping isn't enough because every site would appear as a valid server. Is there any way to tell whether the address is correct and maybe also get some additional information? (Something like the game webpage with the three servers). I didn't want to use the FirstLoad handler because I thought it would create a big amount of traffic.

**Comment by ajanata** [comment]
The server list page uses [stats.jsp](https://pyx-1.pretendyoure.xyz/zy/stats.jsp) to get its information. Not being able to load that page, or not finding those keys on it, prompts the "server down?" message.
