### ISSUE TITLE
Failed to execute goal...

### ISSUE THREAD

**Issue by bdevelops** [ajanata/PretendYoureXyzzy#175]
Whenever I try to build it using maven (following Quickstart Guide) I get [this](https://gist.github.com/bdevelops/81ac8dbe3a814aab4aa550fe5ca9ac28) build failure. Am I missing something? I'm using default build.properties file. This error leads to [this](https://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException) site which says 

> Unlike many other errors, this exception is not generated by the Maven core itself but by a plugin. As a rule of thumb, plugins use this error to signal a problem in their configuration or the information they retrieved from the POM.

What exactly causes this error and how can it be solved? Is it something with git?

Edit: I get something like that even without build.properties file.
Edit2: Turns out I didn't read readme, but after I added `-Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false` to startup command another error occurs, now there's something wrong with address, gist is [here.](https://gist.github.com/bdevelops/fb33826af3108c3efccf881e8918ac1f)

**Comment by devgianlu** [comment]
Something is using port 80, make sure to stop it before launching PYX.

**Comment by ajanata** [comment]
I'm not sure what would be causing the git issues, honestly, but working around it with the flags seems to be working for you.

It's actually port 8080 by default, not port 80. If you can't figure out what's running on that port, you can try to change it with ``-Djetty.http.port=something``.

**Comment by bdevelops** [comment]
I tried to run this today, thought something could change and it would work and guess what, it did. Something was actually running on 8080 I guess, but it stopped after I restarted my computer.
