### ISSUE TITLE
Cant compile through Maven

### ISSUE THREAD

**Issue by RecursionError** [ajanata/PretendYoureXyzzy#178]
I'm having trouble compiling the project through maven using: mvn clean package war:war jetty:run
I have also tried using war:exploded and get the same result
Here is what im getting:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.650 s
[INFO] Finished at: 2018-07-21T20:04:38+00:00
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'runmvn' in plugin org.eclipse.jetty:jetty-maven-plugin:9.3.0.v20150612 among available goals run-forked, run-war, start, effective-web-xml, run, stop, run-exploded, deploy-war, help -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
root@ubuntu-s-1vcpu-1gb-sfo2-01:~/PretendYoureXyzzy# mvn clean package war:war jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pyx 0.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.fasterxml.jackson.core:jackson-core:jar:2.9.2-SNAPSHOT is missing, no dependency information available
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pyx ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-files-exist) @ pyx ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFilesExist failed with message:
Some required files are missing:
/root/PretendYoureXyzzy/build.properties

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.748 s
[INFO] Finished at: 2018-07-21T20:04:57+00:00
[INFO] Final Memory: 11M/26M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-files-exist) on project pyx: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by devgianlu** [comment]
You need to append `-Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false` like so `mvn clean package war:exploded jetty:run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false`.

**Comment by RecursionError** [comment]
that fixed it
