### ISSUE TITLE
"No plugin found for prefix 'war' in the current project

### ISSUE THREAD

**Issue by dinkstr** [ajanata/PretendYoureXyzzy#179]
I can't get the program to compile :(. I'm not sure why, but it's probably my fault. I've re-read the steps and started from the beginning but I still get the same errors. I'm not exactly sure how to copy text from a virtual machine so here's an image https://i.gyazo.com/4fc1ef9be6053579727113147b1d2256.png

It lists a bunch of warnings saying it can't retrieve plugin descriptors until it ultimately fails because 
"No plugin found for prefix 'war' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

**Comment by devgianlu** [comment]
What command did you execute?

**Comment by dinkstr** [comment]
"mvn clean package war:war -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false"
as instructed by the installation guide.

**Comment by devgianlu** [comment]
If you just want to run the server use `mvn clean package war:exploded jetty:run`

**Comment by dinkstr** [comment]
Still get the same warnings and build failure after running that command. It doesn't look like it recognises war at all

**Comment by dinkstr** [comment]
It was probably just a firewall or iptables issue. After installing on a real server box it builds successfully.

**Comment by devgianlu** [comment]
To close the issue, login and then click on the "close issue" button.

**Comment by dinkstr** [comment]
Cheers. Thanks for your help anyway!
