### ISSUE TITLE
Server discovery API

### ISSUE THREAD

**Issue by devgianlu** [ajanata/PretendYoureXyzzy#180]
Since the main server are down many people started their own servers. It would be nice if each server could communicate to a small API that it is alive so that other players can connect to it. This way we would have a network made of self hosted servers that will never go down, like Torrent does.

Just an idea, but I'll probably start developing it soon on my fork.

**Comment by devgianlu** [comment]
Fully implemented on my fork along with the API. To list available servers go [here](https://script.googleusercontent.com/macros/echo?user_content_key=3eql3ogsfak7qa4Q1V3woJKKQ8Ud5wNVLofRUsDk-nV9Jh9-P42zNdukeE5ZS3Y5rSSWVH2Cu-0cvXVezPtcWtGc_bjRSnu_m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnBWIXflQ-CIoBTZ-6ILQ0fFOllMlS__mSV4XOgLTgQjesANyojEIQrarPamO-BZ9CUDVHivpxOgWVBLkkJzmV_8&lib=MnYZbpKncS-3cO3XeBWWFYYHMvCMsVbtx).

**Comment by ajanata** [comment]
That'd be really nice to have in mainline. I do want to update the server landing page to have hosted servers listed, though I'm not sure when I'll have time to do much for a week or so...

**Comment by ajanata** [comment]
Additionally, some sort of way to indicate what version of the server is running would be nice, even if it's just the git commit hash (which should already be in the pyx.build property, I think).

I'll probably work on something similar when I have time.

**Comment by devgianlu** [comment]
If you look at my fork, I've made quite some work, but also some breaking changes. 

- Removed the Tomcat dependency so that it is easier for everyone to execute 
- Reformatted/cleaned up the code
- Fast Heroku deploy
- Configuration file outside of the Jar
- Discovery API

I know this is a lot of stuff to merge, but I think these changes really help the server spreading in cases lile this one.
