### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by matthewnaruzny** [ajanata/PretendYoureXyzzy#191]
While trying to build using the default build command, I receive the error "Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-files-exist)

How do I fix this error?

**Comment by devgianlu** [comment]
Make sure you are executing the right command which is mvn clean package war exploded jetty run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false
