### ISSUE TITLE
How can I remove card packs?

### ISSUE THREAD

**Issue by Benji-Collins** [ajanata/PretendYoureXyzzy#192]
I tried running all sorts of combinations in postgresql but I can't get it to work. Ideally I would just do it with the `watermark` value. What is the correct command(s) to delete certain packs? Thanks.

**Comment by devgianlu** [comment]
If you are an admin you can visit `/cardsets.jsp` and click `delete`. 

Even if the database has a field for `active`, changing it doesn't do anything.

**Comment by ajanata** [comment]
You actually can set it to ignore inactive card sets, that's just [not enabled by default](https://github.com/ajanata/PretendYoureXyzzy/blob/master/build.properties.example#L4). Not sure why I did that.
