### ISSUE TITLE
What settings do i have to change to remove as much tracking/logging as I can?

### ISSUE THREAD

**Issue by Benji-Collins** [ajanata/PretendYoureXyzzy#193]
I don’t want anymore user data than what is absolutely necessary to be logged. What settings/properties should I change to achieve this?

**Comment by devgianlu** [comment]
The default configuration doesn't log anything. If you want to remove the console log set [this](https://github.com/ajanata/PretendYoureXyzzy/blob/8e1c5e805ba323e80804060d22a8a9ddf79dbdbf/src/main/resources/WEB-INF/log4j.properties#L1) line to `log4j.rootLogger=OFF`.

**Comment by ajanata** [comment]
You might still end up with IP addresses in the logs in error situations
with the default config; turn it off entirely as above if you want
absolutely nothing. The default metrics config is completely disabled so
that's fine.

I run my servers with metrics enabled but only warning logging. Cloudflare
has changed something that is causing warning logging with usernames and IP
addresses, so I'll have to look into that sometime cuz I don't want that
either.

**Comment by Benji-Collins** [comment]
Thanks.
