### ISSUE TITLE
Simple questions about where things are located

### ISSUE THREAD

**Issue by Benji-Collins** [ajanata/PretendYoureXyzzy#194]
I have 2 questions about where certain settings/lines are in the source files.

How can I change the first message that the server sends when a game is being made? It currently says `The following Cardcast decks are in use in this game (instructions):` but I want it to say something else. 

How can I change the wait time between the Card Czar picking a winner and the next round starting? It's currently 8 seconds but I want to change it to 5.

Thanks.

**Comment by devgianlu** [comment]
To change the intermission look at [this line](https://github.com/ajanata/PretendYoureXyzzy/blob/8e1c5e805ba323e80804060d22a8a9ddf79dbdbf/src/main/java/net/socialgamer/cah/data/Game.java#L147).

And [here](https://github.com/ajanata/PretendYoureXyzzy/blob/master/WebContent/js/cah.game.js#L814-L823) is the message you are talking about.

**Comment by Benji-Collins** [comment]
Thanks, exactly what I needed.
