### ISSUE TITLE
Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

### ISSUE THREAD

**Issue by Benji-Collins** [ajanata/PretendYoureXyzzy#196]
I ran `apt upgrade` earlier today and now what I try to build the .war with `mvn clean package war:war -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false` I get this error:

`Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter`

This occurs during the test phase. By adding `-Dmaven.test.skip=true` to the end of that command I can skip the test phase and avoid the error. Not sure what's going on there but at least there is a bypass.

If this is something that can't be fixed easily (or has nothing to do with this project) it might be useful to change the recommended build command in the README to:

`mvn clean package war:war -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false -Dmaven.test.skip=true`

**Comment by himokko413** [comment]
As far as I know this has more to do with Java itself and not PYX. Debian (and Ubuntu/offspring) have Java packages that currently have this issue and skipping tests seem to be the only fix for now.
