### ISSUE TITLE
Make incoming messages use a different name tag

### ISSUE THREAD

**Issue by Benji-Collins** [ajanata/PretendYoureXyzzy#198]
As of now, all incoming messages in the chat (from other players) start with `<name>`. I've managed to change this to `Name:`  for messages sent by the player but it still says `<name>` for other players.

Where can I change this? I want all messages from player to start with `Name:`. Thanks.

**Comment by devgianlu** [comment]
https://github.com/ajanata/PretendYoureXyzzy/blob/8e1c5e805ba323e80804060d22a8a9ddf79dbdbf/WebContent/js/cah.longpoll.handlers.js#L140

**Comment by Benji-Collins** [comment]
Thanks.
