### ISSUE TITLE
[11:17:45 PM] Error: You must select at least one base card set. 

### ISSUE THREAD

**Issue by nexusofdoom** [ajanata/PretendYoureXyzzy#200]
![image](https://user-images.githubusercontent.com/16519553/48975819-55ecfa80-f03f-11e8-9c58-1cd8cbb79c63.png)
[11:17:45 PM] Error: You must select at least one base card set.

**Comment by nexusofdoom** [comment]
[WARNING] The POM for com.fasterxml.jackson.core:jackson-core:jar:2.9.2-SNAPSHOT is missing, no dependency information available


[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pyx ---
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom (1.5 kB at 22 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2.0.6/maven-2.0.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven/2.0.6/maven-2.0.6.pom (9.0 kB at 126 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/5/maven-parent-5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/5/maven-parent-5.pom (15 kB at 206 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/3/apache-3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/3/apache-3.pom (3.4 kB at 47 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom (4.1 kB at 52 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/16/spice-parent-16.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/16/spice-parent-16.pom (8.4 kB at 113 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom (8.4 kB at 109 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.jar (13 kB at 150 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar (226 kB at 1.3 MB/s)
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-files-exist) @ pyx ---

**Comment by nexusofdoom** [comment]
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFilesExist failed with message:
Some required files are missing:
/home/cah/PretendYoureXyzzy/build.properties

???

**Comment by devgianlu** [comment]
You need to follow the latest build instructions. In particular, rename
build.properties.example to build.properties.

**Comment by nexusofdoom** [comment]
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.v20150612/jetty-maven-plugin-9.3.0.v20150612.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.v20150612/jetty-maven-plugin-9.3.0.v20150612.pom (6.8 kB at 4.9 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-project/9.3.0.v20150612/jetty-project-9.3.0.v20150612.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-project/9.3.0.v20150612/jetty-project-9.3.0.v20150612.pom (32 kB at 117 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/25/jetty-parent-25.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/25/jetty-parent-25.pom (22 kB at 135 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.v20150612/jetty-maven-plugin-9.3.0.v20150612.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.v20150612/jetty-maven-plugin-9.3.0.v20150612.jar (99 kB at 233 kB/s)
[INFO]
[INFO] ------------------------< net.socialgamer:pyx >-------------------------
[INFO] Building pyx 0.7.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.fasterxml.jackson.core:jackson-core:jar:2.9.2-SNAPSHOT is missing, no dependency information available
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pyx ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-files-exist) @ pyx ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFilesExist failed with message:
Some required files are missing:
/home/travus/PretendYoureXyzzy/build.properties

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.163 s
[INFO] Finished at: 2018-11-25T07:36:30-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-files-exist) on project pyx: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by nexusofdoom** [comment]
![image](https://user-images.githubusercontent.com/16519553/48979776-29f46800-f085-11e8-91e7-9d0bd8bf8aa4.png)

**Comment by nexusofdoom** [comment]
do you have the url for the full build instructions?

Thanks

**Comment by nexusofdoom** [comment]
getting this 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pyx: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?


this is my java 
 java -version
java version "1.7.0_171"
OpenJDK Runtime Environment (IcedTea 2.6.13) (7u171-2.6.13-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.171-b02, mixed mode)

**Comment by nexusofdoom** [comment]
looks like i got it working 

![image](https://user-images.githubusercontent.com/16519553/48979984-83aa6180-f088-11e8-842b-ae8d71e88647.png)

installed debian 7 64 
install java 1.8 

git 
https://github.com/ajanata/PretendYoureXyzzy


install maven 
https://www.tecmint.com/install-apache-maven-on-ubuntu-debian/

mv file build.properties.example to build.properties

then ran 
mvn clean package war:exploded jetty:run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false 

does that look correct ?

**Comment by nexusofdoom** [comment]
how many players needed ?

and if I reboot the box will it start up as a service ?

or do I need to rerun ? 
source /etc/profile.d/maven.sh t

then 

mvn clean package war:exploded jetty:run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false

**Comment by devgianlu** [comment]
Yep

**Comment by nexusofdoom** [comment]
is there a start up script for this?
and this is a local not public server I would need to open ports on firewall so other people to join ?

**Comment by devgianlu** [comment]
You can use [my fork](https://github.com/devgianlu/PretendYoureXyzzy), it isn't updated to the latest features, but you can deploy it on Heroku without any configuration whatsoever.

ATM, this is the only way to setup this version of PYX.
