### ISSUE TITLE
after rebooting server what do I run to start "pretendyourexyzzzy"?

### ISSUE THREAD

**Issue by nexusofdoom** [ajanata/PretendYoureXyzzy#203]
do I always run this ?
mvn clean package war:exploded jetty:run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false

to get it to start?

**Comment by devgianlu** [comment]
Yes, this is the easiest way to run it again because Maven will start Jetty for you.

**Comment by ajanata** [comment]
Unless you want to go through the process of configuring Tomcat and having that run on boot (which is what my servers do), that's probably the best.
