### ISSUE TITLE
Metrics are broken

### ISSUE THREAD

**Issue by devgianlu** [ajanata/PretendYoureXyzzy#207]
Trying to visit any metrics related link will result in a `502`.

https://pretendyoure.xyz/zy/metrics/user/c1c462ee-6b7b-4011-8660-2f69935d1e41

**Comment by ajanata** [comment]
Whoops, forgot to start that back up when the server crashed… I need to make that automatic at some point along with the rest of the metrics infrastructure (which has been running). Should be fine now. Thanks for reporting.
