### ISSUE TITLE
Card cast cards repeating

### ISSUE THREAD

**Issue by altomafone** [ajanata/PretendYoureXyzzy#215]
When playing with 2 card cast decks and 3 built in decks, we've noticed that the same handful of cards from the card cast decks (and maybe the others. Haven't confirmed) repeat on every game and the majority of cards don't get used at all. Is this a known bug? Is there a work around?

**Comment by ajanata** [comment]
Closing this since cardcast shut down.

I'd be very surprised if the RNG is that broken, but I wouldn't say it's impossible...
