### ISSUE TITLE
1) The only thing being an admin really gives you is the ability to chat. I have disabled that on my own servers for a specific reason and if I give one person the ability to chat I have to give everyone the ability to chat. I will not be doing that again.

### ISSUE THREAD

**Issue by stan754** [ajanata/PretendYoureXyzzy#217]
1) The only thing being an admin really gives you is the ability to chat. I have disabled that on my own servers for a specific reason and if I give one person the ability to chat I have to give everyone the ability to chat. I will not be doing that again.
2) This repository is for dealing with issues with the code, not support for the servers I run. Locking this conversation.

_Originally posted by @ajanata in https://github.com/ajanata/PretendYoureXyzzy/pull/216#issuecomment-526284022_

I know but how do i host my own server

**Comment by devgianlu** [comment]
[Install Docker](https://docs.docker.com/install/) then run `docker run -d -p 8080:8080 emcniece/dockeryourxyzzy:dev`. The server is ready, visit `localhost:8080` in your browser.
