### ISSUE TITLE
URL for maven repository in pom.xml no longer working

### ISSUE THREAD

**Issue by professormudd** [ajanata/PretendYoureXyzzy#227]
I was unable to build the war file as maven could not connect to the googlecode URL that is specified in the pom.xml. Is there an alternative URL, or do we need to download the jars manually and change the URL to a local file:// path?

**Comment by Tysseract** [comment]
I changed the geoip version from 2.8.0 to 2.8.1 and it worked...

**Comment by ajanata** [comment]
Sounds like this was fixed in #228
