### ISSUE TITLE
How to enable SSL/TLS?

### ISSUE THREAD

**Issue by Tysseract** [ajanata/PretendYoureXyzzy#229]
Is there any way to add an SSL certificate? I noticed that https://pyx-1.pretendyoure.xyz/ is secure but even with PostgreSQL enabled in config, my instance says connection not secure

**Comment by ajanata** [comment]
Run it behind a reverse proxy. I'm actually using Cloudflare to manage the TLS. If you want tomcat to do it directly, you'd have to consult its documentation.
