### ISSUE TITLE
Languages Translations

### ISSUE THREAD

**Issue by nagybal** [ajanata/PretendYoureXyzzy#231]
I would like to do translations. Is it possible? Or add a deck in Hungarian language maybe?

Please inform me how to do it?

**Comment by ajanata** [comment]
I will not be adding translated decks directly to the game. If you want to add custom/translated decks, put them on https://www.cardcastgame.com/ and you can import the decks: https://github.com/ajanata/PretendYoureXyzzy/wiki/Cardcast

If you want to translate the UI, there is currently no support for multiple languages, but I am not strictly against it.
