### ISSUE TITLE
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) 

### ISSUE THREAD

**Issue by tammybstr** [ajanata/PretendYoureXyzzy#238]
![sc](https://user-images.githubusercontent.com/65306814/81848740-7c616700-954d-11ea-87f5-e98401eaa6f4.PNG)

**Comment by A3K** [comment]
What's your issue here?

**Comment by tammybstr** [comment]
every time i go on the website it loads like this and i can’t play any games

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by A3K** [comment]
Are you unable to scroll down?

**Comment by tammybstr** [comment]
No I can’t scroll down either

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by A3K** [comment]
What happens? Does the scroll bar not move? What if you click and drag the scroll bar?

**Comment by tammybstr** [comment]
there is no scroll except when i try to join a game but when i do it just takes me back to the home and it looks like this[cid:c63e6bdf-d31b-489a-8464-34ef44a4c0b7]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajanata** [comment]
There is definitely a scrollbar on the right side of the screen...

You could also try changing `index.jsp` in the URL to `game.jsp` and bypass that page.

**Comment by tammybstr** [comment]
There isn't. Don't you think I checked MULTIPLE times??? And if you're on about the little scrollbar, that was for the tweets so try again before trying to make me look like I don't know what I'm talking about. Also you didn't even help or resolve my problem, so thanks for nothing.

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ajanata** [comment]
This scroll bar right there. 
![image](https://user-images.githubusercontent.com/1106319/82760348-c9440980-9da7-11ea-83e7-ccda5bfd70e3.png)

**Comment by ajanata** [comment]
Further, I did offer you something else to try in case that scroll bar is actually broken for some reason.
