### ISSUE TITLE
Cardcast data

### ISSUE THREAD

**Issue by ThiefMaster** [ajanata/PretendYoureXyzzy#244]
I don't know if the public xyzzy instances had any caching of cardcast data, but if yes, is there any chance you could publish a public dump of the cached data somewhere? It'd be a shame to lose all the custom sets from cardcast because some jerk sued them...

**Comment by devgianlu** [comment]
I've also thought of that but the cache is stored with a `SoftReference` which is deleted by the garbage collector as soon as it doesn't have any more references to it. After the games using it have been removed it is likely to disappear.

Trying to take a memory dump will do no harm tough.

**Comment by ajanata** [comment]
There's almost certainly nothing left in them after a week. The servers are constantly GCing. This is JVM memory usage for the past day; each time it goes down, the GC has run.

![image](https://user-images.githubusercontent.com/1106319/82743811-2cd92300-9d25-11ea-8ef0-cf15b84af45f.png)
