### ISSUE TITLE
How to access admin page?

### ISSUE THREAD

**Issue by 19wolf** [ajanata/PretendYoureXyzzy#248]
I'm trying to get to the admin page on my server (and I'm not currently on my server's network), what do I do to whitelist myself? Running in Docker if that's relevant.

Search brought me to https://github.com/ajanata/PretendYoureXyzzy/issues/165 but the solution seems out of date.

**Comment by Dalkei** [comment]
Lucky for you, Ajanta has followed through with adding admins to the build properties.

Unlucky for you, you have to build the project again for it to take effect.


https://github.com/ajanata/PretendYoureXyzzy/blob/master/build.properties.example#L16

**Comment by joncamfield** [comment]
Any chance that could be set through Docker environment variables?

**Comment by ajanata** [comment]
> Lucky for you, Ajanta has followed through with adding admins to the build properties.
> 
> Unlucky for you, you have to build the project again for it to take effect.
> 
> https://github.com/ajanata/PretendYoureXyzzy/blob/master/build.properties.example#L16

You can go in and edit the resulting properties file directly without _having_ to do a build.



> Any chance that could be set through Docker environment variables?

There is no official Dockerfile, so you'd have to bring that up with whomever is providing it.
