### ISSUE TITLE
CardCast Replacement

### ISSUE THREAD

**Issue by DeadlySurgeon** [ajanata/PretendYoureXyzzy#249]
Do we have any idea why cardcast was taken down? If it wasn't for DMCA purposes, I could see about getting a replacement mocked up.

**Comment by ajanata** [comment]
> Do we have any idea why cardcast was taken down?

If they haven't said anything, then no.

> I could see about getting a replacement mocked up.

#241, which I will look at as soon as I have some time... I had intended to this week, but I haven't had the free time I expected, so it might have to wait until next weekend unfortunately.
