### ISSUE TITLE
Cant add cardcast

### ISSUE THREAD

**Issue by MikiPoznan** [ajanata/PretendYoureXyzzy#251]
www.cardcastgame.com writes  GAME OVER
and when i try to add New Cardcast it says **_Error: Cannot find Cardcast deck with given ID. If you just added this deck to Cardcast, wait a few minutes and try again._**

**Comment by devgianlu** [comment]
Cardcast has been shutdown. See #240.

**Comment by MikiPoznan** [comment]
> 
> 
> Cardcast has been shutdown. See #240.

Thanks :P  Also is there a way to add a cast than ? || Would like to use F.E. deck UGJCF

**Comment by devgianlu** [comment]
You can play with custom deck on this server: http://pyx.gianlu.xyz/ZY/. You can also download your deck from here: https://pretendyoure.xyz/zy/metrics/deck/UGJCF (https://twitter.com/_PYX_/status/1265851677539614722). Currently, there's no way to import the CSV file into the server.

**Comment by MikiPoznan** [comment]
> 
> 
> You can play with custom deck on this server: http://pyx.gianlu.xyz/ZY/. You can also download your deck from here: https://pretendyoure.xyz/zy/metrics/deck/UGJCF (https://twitter.com/_PYX_/status/1265851677539614722). Currently, there's no way to import the CSV file into the server.

Im little confused... how should i use it? i tried /addcustomdeck_url and it returns  _**Error: Invalid command.**_

**Comment by devgianlu** [comment]
![image](https://user-images.githubusercontent.com/14827249/86542178-a0b93e80-bf13-11ea-8c25-6261fef2647b.png)

You should use the upload JSON button and select a compatible file (see #241). The instructions are a bit lacking on this topic. The Android app makes this a bit easier.

**Comment by MikiPoznan** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/14827249/86542178-a0b93e80-bf13-11ea-8c25-6261fef2647b.png)
> 
> You should use the upload JSON button and select a compatible file (see #241). The instructions are a bit lacking on this topic. The Android app makes this a bit easier.

;-; where should i get the json if im on **_https://pretendyoure.xyz/zy/metrics/deck/UGJCF_**  ???

**Comment by devgianlu** [comment]
There is no way ATM, but I'll create a little website/script to do so tomorrow. Stay tuned.

**Comment by MikiPoznan** [comment]
> so tom

thanks <3 would love to play it with frainds tysm for help

**Comment by devgianlu** [comment]
@ajanata Could you allow CORS on `https://pretendyoure.xyz/zy/metrics/deck/CODE5`? I'd like to make it all client side logic, but it's not possible ATM.

I've converted the deck for you so that you can add it via upload JSON (download it first): https://gist.github.com/devgianlu/929798ea6fb35e95d4520be3ca67d50f

**Comment by MikiPoznan** [comment]
> 
> 
> @ajanata Could you allow CORS on `https://pretendyoure.xyz/zy/metrics/deck/CODE5`? I'd like to make it all client side logic, but it's not possible ATM.
> 
> I've converted the deck for you so that you can add it via upload JSON (download it first): https://gist.github.com/devgianlu/929798ea6fb35e95d4520be3ca67d50f

thanks :P
