### ISSUE TITLE
Manually editing the pyx.sqlite database?

### ISSUE THREAD

**Issue by waterlubber** [ajanata/PretendYoureXyzzy#253]
I'd like to add some custom decks to the pyx.sqlite database, by hand, for my friends and I to play with (as Cardcast is down.) 
How could I go about adding a deck? 
From what I can tell from poking around in an editor,
- Black and white cards are added to their respective tables. They each have unique, sequential `id`, and `draw` and `pick` refer to the "Draw [2], Pick [3]" or other similar cards. `watermark` is an abbreviation from the deck the cards are from.
- `card_set_black_card` matches card set IDs to deck IDs, so `watermark` has no bearing on what deck it's actually from (?) (Likewise for the white card version)
- `card_set` contains names and descriptions for card packs, but I'm not sure what `weight` and `base_deck` do. Do the names and descriptions need to be identical? 

Would I be able to just add my own deck following the above database format and have it load into the game? I'm not entirely sure.

Would I be better off just merging the json pull request?

**Comment by devgianlu** [comment]
> Would I be able to just add my own deck following the above database format and have it load into the game?

If you're using a custom server you could just edit `pyx.sqlite` with https://sqlitebrowser.org/ and it would work as long as you reference the cards correctly.

> Would I be better off just merging the json pull request?

#241 is ready to merge and it is already being used on [my server](http://pyx.gianlu.xyz/ZY/). There's also an [app](https://play.google.com/store/apps/details?id=com.gianlu.pretendyourexyzzy) which provides an easy way to create custom decks. I should also mention CrCast which is being used on [this server](https://xyzzy.clrtd.com/zy/game.jsp).

**Comment by waterlubber** [comment]
I was able to get it working without too much trouble. Do you know what the `weight` factor controls? I would like to increase the chance of cards from my custom deck appearing.

**Comment by devgianlu** [comment]
The only usage of the parameter seems to be [here](https://github.com/ajanata/PretendYoureXyzzy/blob/ed08e371978529db8a908e266dc1a8add1d37967/src/main/java/net/socialgamer/cah/db/PyxCardSet.java#L143).

**Comment by waterlubber** [comment]
Hmm. Maybe it was a half-implemented feature. I'm going to close this issue since I got the database working and all sorted out.
