### ISSUE TITLE
Missing deck

### ISSUE THREAD

**Issue by LucaColombo1990** [ajanata/PretendYoureXyzzy#260]
Hi! 
We're trying to play with this deck https://pretendyoure.xyz/zy/metrics/deck/9ZSQH, but once I write /addcardcast 9ZSQH in the chat the server can't find the deck:
 Error: Cannot find Cardcast deck with given ID. If you just added this deck to Cardcast, wait a few minutes and try again.

**Comment by ajanata** [comment]
Cardcast was shut down in May; you can't use it anymore.
