### ISSUE TITLE
Already used card

### ISSUE THREAD

**Issue by jamesking210** [ajanata/PretendYoureXyzzy#275]
I'm self hosting on docker [emcniece/dockeryourxyzzy:latest] - If I use a white card it doesn't go away and if I try to use it again, it chat's an error i cant use the card and then cant click off it. Eventually it logs the player out of the game. - I'm hosting at https://cards.jimboslicechicago.com so you can try to duplicate it.

**Comment by jamesking210** [comment]
Tested in Chrome/iOS/Firefox, same issues.

**Comment by ajanata** [comment]
Every time? This happens to me once in a very long while and never figured out why, and the easy fix is to just refresh the page or use the `/sync` command. If this is happening very often, then I'm sorry but I really don't have the time to do much maintenance for this anymore (see all the pending PRs that I just haven't looked at).

I honestly probably should just archive the repo, but there really is some cleanup I need to do before I can do that...

**Comment by jamesking210** [comment]
tuns out you are right. I did refresh and it fixed the issue, ill close this.
