### ISSUE TITLE
Is the developent of this site/game still active?

### ISSUE THREAD

**Issue by SecularSteve** [ajanata/PretendYoureXyzzy#277]
I mean, the servers are still running, and the game's as popular as it ever was, but are there any updates and/or bug fixes planned?

It's been 3 years, so I'm asking more out of curiosity. Even the GUI could use a redesign/overhaul in my opinion.

**Comment by ajanata** [comment]
Not really, no. I keep the lights on but I don't really have the motivation to even go through pull requests anymore. I'm pretty much over Java, and certainly over JavaScript and CSS, at this point.
