### ISSUE TITLE
Sometimes when the Czar confirms the winner the next round never starts.

### ISSUE THREAD

**Issue by LJNielsenDk** [ajanata/PretendYoureXyzzy#89]
Been noticing this sporadically for a few days, but it is happening a lot right now.

This happens to the whole game, not just one player not getting updated. The chat still works.

Reloading does nothing. The Czar leaving does nothing other than appoint a new Czar who then has the same cards to pick from but can't actually pick.

**Comment by ajanata** [comment]
This doesn't seem to have been happening anymore.
